models:
  student:
    _target_: fastvideo.train.models.wangame.WanGameCausalModel
    init_from: /mnt/data/world_model/zelda_runs/wangame_self_forcing_zelda/checkpoint-best-step-5600-diffusers
    trainable: true
    transformer_override_safetensor: /mnt/data/world_model/zelda_runs/wangame_dfsft_zelda/checkpoint-50000-diffusers/transformer/model.safetensors
  teacher:
    _target_: fastvideo.train.models.wangame.WanGameModel
    init_from: /mnt/data/world_model/WanGame-2.1-0325-60k-steps
    trainable: false
    disable_custom_init_weights: true
  critic:
    _target_: fastvideo.train.models.wangame.WanGameModel
    init_from: /mnt/data/world_model/WanGame-2.1-0325-60k-steps
    trainable: true
    disable_custom_init_weights: true

method:
  _target_: fastvideo.train.methods.distribution_matching.self_forcing.SelfForcingMethod
  rollout_mode: simulate
  generator_update_interval: 5
  real_score_guidance_scale: 1.0
  dmd_denoising_steps: [1000, 750, 500, 250]

  chunk_size: 3
  student_sample_type: sde
  context_noise: 0.0
  enable_gradient_in_rollout: true
  start_gradient_frame: 0

  # Critic optimizer
  fake_score_learning_rate: 3e-7
  fake_score_betas: [0.0, 0.999]
  fake_score_lr_scheduler: constant

training:
  distributed:
    num_gpus: 32
    sp_size: 1
    tp_size: 1
    hsdp_replicate_dim: 1
    hsdp_shard_dim: 32

  data:
    data_path: >-
      /mnt/data/world_model/zelda-wasd-only:1,
      /mnt/data/world_model/zelda_data/zeldam2-v2:1
    dataloader_num_workers: 4
    train_batch_size: 1
    training_cfg_rate: 0.0
    seed: 1000
    num_latent_t: 9
    num_height: 480
    num_width: 832
    num_frames: 33
    apply_bot_died_filter: false

  optimizer:
    learning_rate: 3e-6
    betas: [0.0, 0.999]
    weight_decay: 0.01
    lr_scheduler: constant
    lr_warmup_steps: 0

  loop:
    max_train_steps: 10000
    gradient_accumulation_steps: 1

  checkpoint:
    output_dir: /mnt/data/world_model/zelda_runs/wangame_sf_zelda_with_longer_dfsft
    training_state_checkpointing_steps: 2000
    checkpoints_total_limit: 3
    best_checkpoint_start_step: 1
    best_checkpoint_top_k: 5

  tracker:
    project_name: wangame_sf
    run_name: zelda_clean_data

  model:
    enable_gradient_checkpointing_type: full

callbacks:
  grad_clip:
    max_grad_norm: 1.0
  validation:
    pipeline_target: fastvideo.pipelines.basic.wan.wangame_causal_dmd_pipeline.WangameCausalSdeDMDPipeline
    scheduler_target: fastvideo.models.schedulers.scheduling_self_forcing_flow_match.SelfForcingFlowMatchScheduler
    dataset_file: examples/training/finetune/WanGame2.1_1.3b_i2v/validation_zelda.json
    every_steps: 200
    sampling_steps: [4]
    sampling_timesteps: [1000, 750, 500, 250]
    num_frames: 33
    guidance_scale: 1.0
    evaluate_ptlflow: true
    ptlflow_dir: /mnt/home/mhuo/ptlflow

pipeline:
  flow_shift: 3
